ServerTokens Prod
ServerSignature Off

<Directory /var/www/html>
    AllowOverride All
    Options FollowSymLinks
    Require all granted
</Directory>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>

<Files "ost-config.php">
    Require all denied
</Files>
