"""
Knowledge Base - Troubleshooting Database (MODERNIZED)

IMPORTANT ⚠️: This KB is now INDEX ONLY (metadata, keywords, symptoms)
NO HARDCODED RESPONSES! All responses are generated dynamically by:
- smart_prompt_engineer.py (intelligent response generation)
- semantic_kb_matcher.py (semantic matching)

The actual troubleshooting steps and first responses are generated by AI,
not hardcoded. This ensures:
✅ Personalized to user skill level
✅ Contextual to their specific problem
✅ No cookie-cutter templates
✅ Continuously improved via effectiven tracking
"""

from typing import Optional, List

# KB Index: Metadata for all troubleshooting categories
# Responses are generated dynamically by AI, not hardcoded here

KB_TROUBLESHOOTING = {
    # ========== GPS & TRACKING ISSUES ==========
    "gps": {
        "category_id": "gps",
        "title": "GPS & Tracking Issues",
        "keywords": ["gps", "lokasi", "location", "tracking", "posisi", "signal", "sinyal", "gps mati", "gps error", "positioning"],
        "description": "Device GPS signal, location accuracy, and real-time tracking issues",
        "symptoms": [
            "GPS tidak akurat",
            "Lokasi tidak update",
            "GPS signal lemah",
            "Device tidak terdeteksi",
            "Heading incorrect",
            "Signal loss",
        ],
        # NOTE: Responses + troubleshooting steps are generated dynamically by AI
        # This JSON is INDEX ONLY for semantic search
        "metadata": {
            "typical_resolution_time": "10-15 minutes",
            "technical_difficulty": "medium",
            "common_root_causes": ["hardware_antenna", "software_config", "environmental", "network"],
            "requires_hardware_access": True,
            "data_loss_risk": False,
        }
    },

    # ========== CONNECTIVITY ISSUES ==========
    "connectivity": {
        "category_id": "connectivity",
        "title": "Internet & Network Connectivity",
        "keywords": ["internet", "signal", "connection", "offline", "tidak connect", "connection failed", "koneksi", "jaringan", "network", "wifi"],
        "description": "Device internet connectivity, mobile data, and server communication issues",
        "symptoms": [
            "Tidak bisa connect ke server",
            "Data tidak tersinkronisasi",
            "Signal lemah",
            "Timeout error",
            "Intermittent connection",
        ],
        # NOTE: Responses generated dynamically
        "metadata": {
            "typical_resolution_time": "5-10 minutes",
            "technical_difficulty": "easy",
            "common_root_causes": ["network_config", "signal_strength", "server_issue", "device_settings"],
            "requires_hardware_access": False,
            "data_loss_risk": False,
        },
    },

    # ========== CAMERA ISSUES ==========
    "camera": {
        "category_id": "camera",
        "title": "Camera & Video Recording Issues",
        "keywords": ["kamera", "camera", "video", "rekam", "recording", "feed", "video feed", "display", "preview", "black screen", "blur", "fokus", "exposure"],
        "description": "Device camera hardware issues, video recording failures, live streaming problems, image quality issues",
        "symptoms": [
            "Kamera tidak berfungsi",
            "Video blur/tidak jelas",
            "Gambar hitam atau tidak ada feed",
            "Recording gagal",
            "Fokus tidak berfungsi",
            "Exposure/brightness masalah",
            "Camera crash",
        ],
        "solutions_hint": [
            "1. Bersihkan lensa kamera",
            "2. Restart device/app",
            "3. Clear camera app cache",
            "4. Check camera permissions",
            "5. Hardware troubleshoot",
        ],
        "metadata": {
            "typical_resolution_time": "10-20 minutes",
            "technical_difficulty": "medium",
            "common_root_causes": ["lens_dirty", "app_bug", "permission_denied", "hardware_failure", "driver_issue"],
            "requires_hardware_access": True,
            "data_loss_risk": False,
        },
    },

    # ========== DEVICE ISSUES ==========
    "device": {
        "category_id": "device",
        "title": "Device Hardware & Software Issues",
        "keywords": ["device", "crash", "freeze", "restart", "reboot", "boot", "not responding", "error", "device tidak mau", "panas"],
        "description": "Device hardware failures, software crashes, performance issues, battery/storage problems",
        "symptoms": [
            "Device restart sendiri",
            "App freeze/hang",
            "Device sangat panas",
            "Battery cepat habis",
            "Storage penuh",
            "Not responding",
        ],
        # NOTE: Responses generated dynamically
        "metadata": {
            "typical_resolution_time": "15-20 minutes",
            "technical_difficulty": "medium",
            "common_root_causes": ["memory_leak", "storage_full", "thermal_issue", "software_bug"],
            "requires_hardware_access": True,
            "data_loss_risk": True,  # "Clear Data" step has data loss risk
        },
    },

    # ========== VEHICLE BREAKDOWN ISSUES ==========
    "vehicle": {
        "category_id": "vehicle",
        "title": "Vehicle Breakdown & Engine Issues",
        "keywords": ["mogok", "stall", "breakdown", "mesin mati", "mesin tidak hidup", "engine stop", "tidak mau hidup", "mobil mogok", "truk mogok", "engine"],
        "description": "Vehicle mechanical failures, engine issues, breakdown on road",
        "symptoms": [
            "Kendaraan mogok/stall di jalan",
            "Mesin mati tiba-tiba",
            "Mesin tidak bisa di-start",
            "Performa mesin menurun",
            "Suara mesin aneh",
            "Smoke atau leak",
        ],
        # NOTE: Responses generated dynamically
        "metadata": {
            "typical_resolution_time": "30-60 minutes",
            "technical_difficulty": "high",
            "common_root_causes": ["fuel_issue", "battery_dead", "engine_failure", "transmission"],
            "requires_hardware_access": True,
            "data_loss_risk": False,
            "critical": True,  # Safety critical issue
        },
    },

    # ========== APP ISSUES ==========
    "app": {
        "category_id": "app",
        "title": "Application & Software Issues",
        "keywords": ["app", "aplikasi", "crash", "error", "force close", "bug", "tidak jalan", "error code", "login", "blank screen"],
        "description": "Application crashes, login failures, feature bugs, data sync issues",
        "symptoms": [
            "App force close",
            "Can't login",
            "Data tidak tersimpan",
            "Feature tidak berfungsi",
            "Blank screen",
            "Connection error",
        ],
        # NOTE: Responses generated dynamically
        "metadata": {
            "typical_resolution_time": "5-15 minutes",
            "technical_difficulty": "easy",
            "common_root_causes": ["app_bug", "outdated_version", "corrupted_cache", "server_issue"],
            "requires_hardware_access": False,
            "data_loss_risk": False,
        },
    },

    # ========== TICKET CREATION ISSUES ==========
    "ticket": {
        "category_id": "ticket",
        "title": "Ticket Creation & Support",
        "keywords": ["tiket", "ticket", "create", "buat", "support", "issue", "lapor", "report", "help"],
        "description": "Issues creating support tickets, getting help, documentation",
        "symptoms": [
            "Tidak bisa buat tiket",
            "Tiket tidak tersimpan",
            "Tiket tidak masuk ke system",
            "Attachment upload gagal",
            "Support tidak respond",
        ],
        # NOTE: Responses generated dynamically
        "metadata": {
            "typical_resolution_time": "5 minutes",
            "technical_difficulty": "easy",
            "common_root_causes": ["form_error", "network_issue", "server_maintenance", "user_error"],
            "requires_hardware_access": False,
            "data_loss_risk": False,
            "meta_issue": True,  # This is a "help with help" issue
        },
    },
}

# ============================================================================
# KB UTILITY FUNCTIONS (INDEX-BASED, NO HARDCODED RESPONSES)
# ============================================================================

def get_kb_category(keywords: List[str]) -> Optional[dict]:
    """Find KB category metadata based on keywords
    
    Returns category metadata for semantic matching, NOT the hardcoded responses
    """
    for category, kb_data in KB_TROUBLESHOOTING.items():
        if any(kw.lower() in ' '.join(keywords).lower() for kw in kb_data["keywords"]):
            return {"category": category, **kb_data}
    return None


def get_category_by_id(category_id: str) -> Optional[dict]:
    """Get KB category metadata by ID"""
    return KB_TROUBLESHOOTING.get(category_id)


def search_kb_symptoms(symptoms: List[str]) -> list:
    """Search KB for matching categories based on symptoms
    
    Returns list of matching categories with similarity scores
    """
    matches = []
    for category, kb_data in KB_TROUBLESHOOTING.items():
        kb_symptoms = kb_data.get("symptoms", [])
        match_count = sum(1 for sym in symptoms if sym in kb_symptoms)
        if match_count > 0:
            similarity = match_count / max(len(symptoms), len(kb_symptoms))
            matches.append({
                "category": category,
                "match_count": match_count,
                "similarity_score": similarity,
                "metadata": kb_data,
            })
    
    # Sort by similarity
    matches.sort(key=lambda x: x["similarity_score"], reverse=True)
    return matches


def get_all_keywords() -> set:
    """Get all keywords from KB for indexing/search"""
    all_keywords = set()
    for kb_data in KB_TROUBLESHOOTING.values():
        all_keywords.update(kb_data.get("keywords", []))
    return all_keywords


def get_all_categories() -> list:
    """Get list of all categories for UI dropdown/selection"""
    return [
        {
            "id": kb_data["category_id"],
            "title": kb_data["title"],
            "difficulty": kb_data["metadata"].get("technical_difficulty", "unknown"),
            "typical_time": kb_data["metadata"].get("typical_resolution_time", "unknown"),
        }
        for kb_data in KB_TROUBLESHOOTING.values()
    ]


if __name__ == "__main__":
    """Test KB index"""
    print("✅ KB Troubleshooting Index Loaded")
    print(f"   Total categories: {len(KB_TROUBLESHOOTING)}")
    print(f"   Total keywords: {len(get_all_keywords())}")
    print(f"\n📚 Available categories:")
    for cat in get_all_categories():
        print(f"   - {cat['id']}: {cat['title']} (Difficulty: {cat['difficulty']})")

